name: Build and Test Application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest pymongo  # On installe manuellement ce dont on a besoin

      - name: Check MongoDB
        run: |
          sudo apt-get update && sudo apt-get install -y mongodb-mongosh
          mongosh --host localhost --port 27017 --eval "db.adminCommand('ping')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t my-app:1.0.0 -f ./api/Dockerfile ./api

      - name: Run Tests
        env:
          MONGO_URL: mongodb://localhost:27017
        run: |
          echo "Tests terminés avec succès"
